### ISSUE TITLE
ImageMagick deprecated?

### ISSUE THREAD

**Issue by aethelwulffe** [SunCoastConnection/TheRealLibreEHR#575]
Document images in Dems/Report (custom_report.php) not converting to JPEG.  Narrative error says "Perhaps Imagemagick is not installed?"
ImageMagick is a deprecated package (reportedly).

**Comment by aethelwulffe** [comment]
@marcusbow is this fixed?  Related to Portal settings?

**Comment by muarachmann** [comment]
You just need to install Imagemagick on your system https://imagemagick.org/script/download.php

**Comment by marcusbow** [comment]
My machine had dependencies that hadnt been updated to satisfy ImageMagick. A new install on another machine had routes to those updated dependencies
